---
title: "day7"
author: "jaanekaraster"
date: "2022-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
#https://www.neonscience.org/resources/learning-hub/tutorials/raster-data-r
library(qgisprocess)
library(terra)
library(rgdal)
library(raster)
library(ggplot2)
library(dplyr)

GDALinfo("50n150e_20101117_gmted_dsc300.tif")
r2020 = raster("50n150e_20101117_gmted_dsc300.tif")
nlayers(r2020) # check number of layers

r2020_df <- as.data.frame(r2020, xy = TRUE) #convert raster to df for ggplot2

r2020@crs # check the CRS
r2020@extent # check the extent in degrees
summary(r2020_df) #get to know the columns of the df

```
```{r hist}
# the distribution of values in the raster, to check if there are any weird values
hist(r2020, main="Distribution of elevation values", 
     col= "purple", 
     maxpixels=22000000)
```

```{r plotting}
# you can plot the raster 
plot(r2020, main="Digital Elevation Model, SJER")
# or if it's a large raster, you can use the image command
image(r2020)
# specify the limits in elevation you want
image(r2020,zlim=c(1,2000))
# add colors
col <- terrain.colors(10)
image(r2020, zlim=c(1,2000), main="Digital Elevation Model (DEM)", col=col)

# add breaks to the colormap (6 breaks = 5 segments)
brk <- c(1,50,500,1000,1500,2000,2500,3000,3500,4000,4500)
plot(r2020,col=col,breaks=brk,main="DEM with more breaks")
```
```{r legends}
# First, expand right side of clipping rectangle to make room for the legend
# turn xpd off
par(xpd = FALSE, mar=c(5.1, 4.1, 4.1, 4.5))

# Second, plot w/ no legend
plot(r2020, col=col, breaks=brk, main="DEM with a Custom (but flipped) Legend", legend = FALSE)

# Third, turn xpd back on to force the legend to fit next to the plot.
par(xpd = TRUE)

# Fourth, add a legend - & make it appear outside of the plot
legend(par()$usr[2], 2,
        legend = c("lowest", "a bit higher", "middle ground", "higher yet", "highest"), 
        fill = rev(col))
```

```{r crop}
#define the crop extent
cropbox2 <-c(154,165,50,62)
#crop the raster
DEMcrop2 <- crop(r2020, cropbox2)
#plot cropped DEM
col <- terrain.colors(10)
brk <- c(1,250,500,1000,2000,4000)

par(xpd = FALSE, mar=c(2,2,2,2))
plot(DEMcrop2,
     col=col,
     breaks = brk,
     xlim=c(154,165),
     ylim=c(50,62), 
     main = "DEM Elevation (m) of Kamchatka Peninsula",
     axes=FALSE, 
     legend = TRUE)


#par(xpd = TRUE)

#legend(par()$usr[2], 152,title="Elevation (m)", legend = brk,fill = rev(col))

```

```{r use-ggplot}
library(viridis)
library(ggthemes)
ggplot() +  
  geom_tile(data=r2020_df, aes(x=x, y=y, fill=X50n150e_20101117_gmted_dsc300), alpha=0.8) + 
  scale_fill_viridis() +
  coord_equal() +
  theme_map() +
  theme(legend.position="bottom") +
  theme(legend.key.width=unit(2, "cm"))


```
