---
title: "day16"
author: "jaanekaraster"
date: "2022-11-16"
output: html_document
---
## Minimal
How minimal can you go?

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Dromiciops gliroides
GBIF.org (19 November 2022) GBIF Occurrence Download https://doi.org/10.15468/dl.defuz7

```{r get-data}
#dromiciops data
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyr) # to clean up NA's
library(ggplot2)
library(jpeg)
library(patchwork)
library(extrafont) # for new fonts
library(remotes) # for installing fonts
library(png)
library(grid)
#remotes::install_version("Rttf2pt1", version = "1.3.8")
#pkgbuild::check_build_tools(debug=TRUE)
#extrafont::font_import()

#image
path = "day16/dromiciops.png"
img = readPNG(path, native = TRUE)
g = grid.raster(img, interpolate=TRUE)

#inset map
geom_bbox = st_as_sfc(st_bbox(c(xmin = -80, xmax = -70, ymin = -33, ymax = -45),crs = st_crs(4326)))
ggm1 = ggplot(data = world) +
     geom_sf(fill = "white") + 
    geom_sf(data = geom_bbox, fill = NA, color = "red", size = 0.8) +
      coord_sf(xlim = c(-85, -32), ylim = c(15,-60), expand = FALSE) + theme_void() 

#read in the CSV's
#CSV to sf object
df = read.csv("day16/dromiciops.csv")
df = df[!(is.na(df$decimalLatitude)),]

d_data = st_as_sf(df, coords=c("decimalLongitude","decimalLatitude"), crs=4326)

#get natural earth layers
world <- ne_countries(scale='medium',returnclass = 'sf')
urban_areas = ne_download(scale = 50, type = 'urban_areas', category = 'cultural',returnclass = 'sf')
#pop = ne_download(scale = 110, type = 'populated_places', category = 'cultural',returnclass = 'sf')
my_y_title = expression(paste(italic("Dromiciops gliroides"), ": Minimal Marsupial"))

#plot the map
ggplot(data = world) +
     geom_sf(fill = "white") + 
  geom_sf(data = urban_areas, colour = "black")+
  #geom_sf(data = pop, colour = "black") + 
    geom_sf(data = d_data, colour = "green", size = 0.5) +
    annotate(geom = "text", x = -75, y = 15, label = "Caribbean Sea", 
    fontface = "italic", color = "grey22", size = 3) +
    annotate(geom = "text",
             x = -90, 
             y = 5, 
             label = "Pacific Ocean", 
    fontface = "italic", 
    color = "grey22", 
    size = 3) +
    coord_sf(xlim = c(-80, -70), ylim = c(-33,-45), expand = FALSE) +
    theme(
      plot.title = element_text(hjust = 0.5, size = 20, face = "bold", color="black"), 
      plot.subtitle = element_text(hjust = 0.5), 
      legend.position = "none", 
      axis.line = element_blank(), 
  axis.text.x = element_blank(), 
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  axis.title.x = element_blank(), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
      panel.background = element_rect(fill = "skyblue"),
     panel.border = element_rect(fill = NA)) + 
  labs(
    x = "", 
    y = "", 
    title = "Monito del Monte", 
    subtitle = my_y_title, 
    caption = "@jaanekaraster | Data: GBIF.org, Natural Earth") +  
  ggspatial::annotation_scale(
    location = "bl",
    bar_cols = c("grey30", "white"),
    text_family = "Maiandra GD"
  ) +
  ggspatial::annotation_north_arrow(
    location = "bl", which_north = "true",
    pad_x = unit(0.2, "in"), pad_y = unit(0.4, "in"),
    style = ggspatial::north_arrow_nautical(
      fill = c("grey40", "white"),
      line_col = "grey20",
      text_family = "Arial"
    )
  ) +
   inset_element(p = ggm1,
                left = 0,
                bottom = 0.7,
                right = 0.3,
                top = 1,
                clip = TRUE) +
    theme(rect = element_rect(fill = "transparent")) + 
  inset_element(p = img,
                left = 1, bottom = 0.7, right = 0.3,top = 1, clip = FALSE)


ggsave("day16/day16.png")



```