---
title: "day22"
author: "jaanekaraster"
date: "2022-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
#install.packages(
#c("ggOceanMapsData", "ggOceanMaps", "ncdf4"),repos = #c("https://cloud.r-project.org","https://mikkovihtakari.github.io/drat"))

library(ggOceanMapsData)
library(ggOceanMaps)
library(ncdf4)
basemap(limits = -50, glaciers = TRUE, bathymetry = T)

ggsave("day22/day22.png")


```


```{r code}

require(maptools)
library(maptools)

data(wrld_simpl)
plot(wrld_simpl)
shp = wrld_simpl[which(wrld_simpl$NAME=="Antarctica"),]
shp = spTransform(shp,"+init=EPSG:3031")
plot(shp)
```


```{r leaflet}
library(leaflet)
startZoom <- 7

crsAntartica <-  leafletCRS(
  crsClass = 'L.Proj.CRS',
  code = 'EPSG:3031',
  proj4def = '+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs',
  resolutions = c(8192, 4096, 2048, 1024, 512, 256),
  origin = c(-4194304, 4194304),
  bounds =  list( c(-4194304, -4194304), c(4194304, 4194304) )
)

mps <- leaflet(options = leafletOptions(crs = crsAntartica, minZoom = 0, worldCopyJump = FALSE)) %>%
    setView(0, -90, startZoom) %>%
    #addCircleMarkers(lng = g$longitude, lat = g$latitude, group = "placenames",
     #                popup = popup, label = g$place_name,
      #               fillOpacity = 0.5, radius = 8, stroke = FALSE, color = "#000",
			#		 labelOptions = labelOptions(textOnly = FALSE)) %>%
    addWMSTiles(baseUrl = "https://maps.environments.aq/mapcache/antarc/?",
                layers = "antarc_ramp_bath_shade_mask",
                options = WMSTileOptions(format = "image/png", transparent = TRUE),
                attribution = "Background imagery courtesy <a href='http://www.environments.aq/'>environments.aq</a>")

mps
```






